CREATE OR REPLACE PROCEDURE PIA_ADMIN."WEB_GETQQEMPLOYEELIST"(
   pCARTID  IN  NUMBER,
   v_refcur OUT Sys_Refcursor)
AS
BEGIN
   OPEN v_refcur FOR
      SELECT ROWID,
         EMPLOYEENAME
     FROM WEB_QQCART
     WHERE CART=pCARTID AND
        EMPLOYEETYPEID=0;
END;
/
