CREATE OR REPLACE PROCEDURE PIA_ADMIN."WEB_QQCOMPARECARTDELETE"(
    pcartid NUMBER,
    pplanid NUMBER)
AS
BEGIN
   DELETE FROM WEB_QQCOMPARECART
      WHERE CART=pcartid and
         PLANID = pplanid;
   COMMIT;
END;
/
