CREATE OR REPLACE PROCEDURE PIA_ADMIN.WEB_CHECKZIPCODE(
    pZipcode IN NUMBER,
    pCount  OUT NUMBER)
AS
BEGIN
    SELECT COUNT(1) INTO pCount
    FROM newZipCode
    WHERE zipcode  = pZipcode;
END;
/
