CREATE OR REPLACE PROCEDURE PIA_ADMIN."WEB_INSERTSAVEQUOTE"(
    pCARTID    NUMBER,
    pLABELNAME VARCHAR2,
    pCREATEDBY VARCHAR2)
AS
BEGIN
   UPDATE WEB_QQEMPLOYER
      SET LABELNAME = pLABELNAME,
         CREATEDBY = pCREATEDBY,
         QUOTENUM = QQEMPLOYER_SEQ.nextval,
         ISSAVED = 'Y',
         DATESAVED = sysdate
      WHERE CART=pCARTID;
   COMMIT;
END;
/
