CREATE OR REPLACE PROCEDURE PIA_ADMIN."WEB_UPDATECOMPARECART"(
   pCARTID NUMBER,
   pPLANID NUMBER)
AS
BEGIN
   UPDATE WEB_QQCOMPARECART
      SET PLANID = pPLANID
      WHERE CART=pCARTID;
   COMMIT;
END;
/
