CREATE TABLE WEB_OESTATUS 
   (	"ID" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(20 BYTE),
	 CONSTRAINT "WEB_OESTATUS_PK" PRIMARY KEY ("ID")
   );

CREATE UNIQUE INDEX PIA_ADMIN.WEB_OESTATUS_PK ON PIA_ADMIN.WEB_OESTATUS
(ID);