CREATE TABLE WEB_USERS 
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"WEBUSERROLEID" NUMBER(8,0), 
	"WEBNAME" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(10 BYTE), 
	"EMPLOYERID" NUMBER(8,0), 
	"EMPLOYEEID" NUMBER(8,0), 
	"MEMBERID" NUMBER(8,0), 
	"UPDATED" DATE, 
	"UPDATEDBY" VARCHAR2(10 BYTE), 
	"LASTLOGINTIME" DATE, 
	"LASTLOGINIP" VARCHAR2(15 BYTE), 
	"ISLOCKOUT" NUMBER(1,0), 
	 CONSTRAINT "WEB_USERS_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "WU$FK$BROKER" FOREIGN KEY (BROKERID) REFERENCES PIA_ADMIN.BROKER (BROKERID)
   );

CREATE UNIQUE INDEX PIA_ADMIN.WEB_USERS_PK ON PIA_ADMIN.WEB_USERS
(ID);

