CREATE TABLE PIA_ADMIN.WEB_RENEWALPLANS
(
  PLANID      NUMBER(6),
  PLANTYPEID  NUMBER(3),
  CART        NUMBER(8)                         NOT NULL
);

CREATE INDEX wrp$multi1 ON web_renewalPlans(cart, planId);

ALTER TABLE PIA_ADMIN.WEB_RENEWALPLANS ADD (
  CONSTRAINT FK_RENEWAL_PLANID 
  FOREIGN KEY (PLANID) 
  REFERENCES PIA_ADMIN.PLANS (PLANID));