CREATE TABLE WEB_ROLES
   (	"WEBUSERROLEID" NUMBER(2,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "WEB_ROLES_PK" PRIMARY KEY ("WEBUSERROLEID")
   );

CREATE UNIQUE INDEX PIA_ADMIN.WEB_ROLES_PK ON PIA_ADMIN.WEB_ROLES
(WEBUSERROLEID);


ALTER TABLE PIA_ADMIN.WEB_ROLES ADD (
  CONSTRAINT WEB_ROLES_PK
  PRIMARY KEY
  (WEBUSERROLEID)
  USING INDEX PIA_ADMIN.WEB_ROLES_PK
  ENABLE VALIDATE);