 CREATE TABLE WEB_OEREJECTIONHISTORY
   (	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"OEID" NUMBER(8,0) NOT NULL ENABLE, 
	"REJECTEDBY" VARCHAR2(10 BYTE), 
	"REJECTEDDATE" DATE, 
	"REJECTIONREASON" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "WEB_OEREJECTIONHISTORY_PK" PRIMARY KEY ("ID")
   )