  CREATE TABLE WEB_OEBENEFICIARIES
CREATE TABLE PIA_ADMIN.WEB_OEBENEFICIARIES
(
  OEID            NUMBER(8)                     NOT NULL,
  MEMBERID        NUMBER(8),
  PLANTYPEID      NUMBER(2),
  FIRSTNAME       VARCHAR2(22 BYTE),
  MIDDLEINITIAL   VARCHAR2(1 BYTE),
  LASTNAME        VARCHAR2(30 BYTE),
  ADDRESS         VARCHAR2(80 BYTE),
  CITY            VARCHAR2(20 BYTE),
  STATE           VARCHAR2(2 BYTE),
  ZIP             VARCHAR2(9 BYTE),
  PERCENTAGE      NUMBER(5,2),
  SOCSECNBR       VARCHAR2(9 BYTE),
  UPDATED         DATE,
  UPDATEDBY       VARCHAR2(20 BYTE),
  RELATIONSHIPID  NUMBER(2)
);
 
