CREATE TABLE WEB_OELEGALDOCS 
(	
  "ID" NUMBER(2,0) NOT NULL ENABLE, 
  "DESCRIPTION" VARCHAR2(200 BYTE), 
	"LEGALCONTENT" VARCHAR2(4000 BYTE),
	"LEGALCONTENTHTML" VARCHAR2(4000 BYTE), 
	"CARRIERID" NUMBER(3,0),
	"CREATED" DATE, 
	"CREATEDBY" VARCHAR2(10 BYTE), 
	"MODIFIED" Date, 
	"MODIFIEDBY" VARCHAR2(10 BYTE), 
	 Constraint "WEB_OELEGALDOCS_PK" Primary Key ("ID")
);