CREATE TABLE PIA_ADMIN.WEB_ENROLLERFORMPLANS
(
  ID               NUMBER(8)                    NOT NULL,
  OEID             NUMBER(8)                    NOT NULL,
  EMPLOYEEID       NUMBER(8)                    NOT NULL,
  MEMBERID         NUMBER(8)                    NOT NULL,
  PLANID           NUMBER(8)                    NOT NULL,
  EFFECTIVEDATE    DATE,
  PLANOFFICE1      VARCHAR2(40 BYTE),
  PLANOFFICE2      VARCHAR2(30 BYTE),
  INSURANCEAMOUNT  NUMBER(10,2),
  PLANOFFICE3      VARCHAR2(40 BYTE),
  PLANOFFICE4      VARCHAR2(40 BYTE),
  EXPIRYDATE       DATE,
  MEMBERPLANID     NUMBER(8),
  TREASONID        NUMBER(2),
  UPDATEDBY        VARCHAR2(20 BYTE),
  UPDATED          DATE,
  PRICE            NUMBER(12,2)
);

CREATE UNIQUE INDEX PIA_ADMIN.ENROLLERFORM_PK ON PIA_ADMIN.WEB_ENROLLERFORMPLANS
(ID);
CREATE INDEX PIA_ADMIN.OEID$ENROLLERFORPLANS ON PIA_ADMIN.WEB_ENROLLERFORMPLANS
(OEID);
ALTER TABLE PIA_ADMIN.WEB_ENROLLERFORMPLANS ADD (
  CONSTRAINT ENROLLERFORM_PK
  PRIMARY KEY
  (ID)
  USING INDEX PIA_ADMIN.ENROLLERFORM_PK;