CREATE TABLE PIA_ADMIN.WEB_RENEWAL
(
  RENEWALID           NUMBER(8)                 NOT NULL,
  EMPLOYERID          NUMBER(8)                 NOT NULL,
  STATE               NUMBER(2),
  ISCOMPLETE          CHAR(1 BYTE)              DEFAULT 'N',
  CONTRIBUTIONTYPEID  NUMBER(3),
  RENEWALDATE         DATE,
  ISPERCENT           CHAR(1 BYTE),
  ISOVERALL           CHAR(1 BYTE),
  NAME                VARCHAR2(60 BYTE),
  TITLE               VARCHAR2(30 BYTE),
  EFFECTIVEDATE       DATE,
  CART                NUMBER(8)                 NOT NULL
);

CREATE INDEX RENEWAL_PK ON WEB_RENEWAL(RENEWALID);

ALTER TABLE PIA_ADMIN.WEB_RENEWAL ADD (
  CONSTRAINT RENEWAL_PK
  PRIMARY KEY
  (RENEWALID)
  USING INDEX PIA_ADMIN.RENEWAL_PK);

ALTER TABLE PIA_ADMIN.WEB_RENEWAL ADD (
  CONSTRAINT FK_CONTRIBUTIONTYPE 
  FOREIGN KEY (CONTRIBUTIONTYPEID) 
  REFERENCES PIA_ADMIN.CONTRIBUTIONTYPE (CONTRIBUTIONTYPEID)
  ENABLE VALIDATE,
  CONSTRAINT FK_EMPLOYERID 
  FOREIGN KEY (EMPLOYERID) 
  REFERENCES PIA_ADMIN.EMPLOYER (EMPLOYERID));
