USE [pibtweb]
GO

/****** Object:  Table [dbo].[Web_OESignatrue]    Script Date: 07/04/2013 19:06:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Web_OESignatrue](
	[OEId] [bigint] NOT NULL,
	[Signatrue] [image] NULL,
 CONSTRAINT [PK_Web_OESignatrue] PRIMARY KEY CLUSTERED 
(
	[OEId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

